fix MSVC error C2440: 'static_cast': cannot convert from 'thandle_t' to 'OIIO_v2::Filesystem::IOProxy *': Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or parenthesized function-style cast